{"uuid": "79f54a22-ec9a-49df-9238-9ddadc527304", "children": ["0ca873d5-f404-4f85-8c00-421d3ef52708", "a8d7d7f9-21b7-4abd-9da3-82773d382fcf", "82c7e9ba-1515-4812-ac3d-c98461fa1bb1", "bdf51cd4-a218-465d-91ef-09fc465722c5"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"/Users/ilonapetenko/Documents/test_task-main/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/tests/conftest.py\", line 37, in driver\n    options.load_capabilities(android_get_desired_capabilities())\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/utils/android_utils.py\", line 22, in android_get_desired_capabilities\n    'udid': udid[1],\n            ~~~~^^^\n"}, "start": 1730748168332, "stop": 1730748168346}], "start": 1730748168332, "stop": 1730748168372}