{"uuid": "acbfd16c-e26c-4202-939b-86456bd34649", "children": ["4b9a3021-4282-489c-af96-883ffb41f567", "d5830f86-1e71-4d3a-8d1f-2b47be7a1fff", "239d62eb-bd8c-4ff2-92f6-d3497f1f1d3f", "708651ac-4b3f-4603-81c6-938e550fc199"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"/Users/ilonapetenko/Documents/test_task-main/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/tests/conftest.py\", line 37, in driver\n    options.load_capabilities(android_get_desired_capabilities())\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/utils/android_utils.py\", line 22, in android_get_desired_capabilities\n    'udid': udid[0],\n            ~~~~^^^\n"}, "start": 1730748113890, "stop": 1730748114039}], "start": 1730748113890, "stop": 1730748114093}