{"uuid": "da129e77-29f9-4673-82a8-dce92b1350d0", "children": ["0c426d39-6b4a-4b5d-8763-a13623aab152", "b80148f0-b04d-40df-8ac8-837b074093bc", "3c48e8e5-beaf-435f-bed1-8484faa3d9db", "c6de3f75-31e7-4247-adae-b3b8aa373147"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"/Users/ilonapetenko/Documents/test_task-main/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/tests/conftest.py\", line 37, in driver\n    options.load_capabilities(android_get_desired_capabilities())\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/utils/android_utils.py\", line 22, in android_get_desired_capabilities\n    'udid': udid[0],\n            ~~~~^^^\n"}, "start": 1730748114062, "stop": 1730748114072}], "start": 1730748114062, "stop": 1730748114093}